"""Update Category model and relationship with Post

Revision ID: 95851d1fa300
Revises: 48b6c19944f5
Create Date: 2023-04-06 13:39:55.745801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95851d1fa300'
down_revision = '48b6c19944f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryname', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('category_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['categoryname'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('category_name_key', ['name'])
        batch_op.drop_column('categoryname')

    # ### end Alembic commands ###
